# Generated by Django 4.2.1 on 2023-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_candidate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='quizid',
            field=models.IntegerField(default=0),
        ),
    ]
