# Generated by Django 4.2.1 on 2023-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_code_quizid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='answered_qn',
            new_name='correct_qn',
        ),
        migrations.AddField(
            model_name='candidate',
            name='wrong_qn',
            field=models.IntegerField(default=0),
        ),
    ]
