# Generated by Django 4.2.1 on 2023-05-28 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_answered_qn_candidate_correct_qn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='quiz_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
